language: generic 
sudo: required
services:
 -docker

before_install:
 -docker build -t avinashclp/docker-react -f Dockerfile.dev .

script:
 -docker run -e CI=true avinashclp/docker-react npm run test